<?php

/**
 * Implements template_preprocess_paragraph().
 */


/**
 * Implements hook_preprocess_node().
 */


/**
 * Implements hook_preprocess_page().
 */

/**
 * Implements hook_preprocess_image().
 */

/**
 * Implements hook_js_alter().
 */

/**
 * Implements hook_preprocess_html().
 */

function test_preprocess_html(array &$variables) {
  $variables['#attached']['library'][] = 'test/general';
}
