version: '3.1'

services:

  test-drupal-9:
    build: .
    ports:
      - 9876:80
    volumes:
      - ./html:/var/www/html
    restart: always
    container_name: test_drupal_9

  test-mysql-drupal-9:
    image: mysql:5.7
    command:
      'mysqld --max-allowed-packet=67108864'
    ports:
      - 3320:3306
    volumes:
      - ./mysql/runtime2:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    container_name: test_mysql_drupal_9

  leumi-sass-drupal-9:
    build: ./sass-watcher
    volumes:
      - ./html/web/themes/custom/test/sass:/sass
      - ./html/web/themes/custom/test/css:/css
    restart: always
    container_name: test_sass_drupal_9


  test-phpmyadmin-drupal-9:
    depends_on:
      - test-mysql-drupal-9
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: test_phpmyadmin_drupal_9
    ports:
      - 6655:80
    environment:
      PMA_HOST: test-mysql-drupal-9
      MYSQL_ROOT_PASSWORD: root

